### ISSUE TITLE
对src/renderer/domUpMessages.js修改出现bug

### ISSUE THREAD

**Issue by xmexg** [Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote#64]
对[src/renderer/domUpMessages.js](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote/blob/51d3f31a9d649a828123b2b11acbffe55d75c14d/src/renderer/domUpMessages.js)修改在这次提交中: https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote/commit/51d3f31a9d649a828123b2b11acbffe55d75c14d#diff-f140b2cb065f33a25b2c7e1620d1843b4f8bc7a79507c17c1e341c4ff47cf910  

使用网页预览时稳定触发bug:  
``` javascript
Uncaught TypeError: Cannot read properties of null (reading 'textContent')
    at domUpMessages (local:////opt/LiteLoader/plugins/LiteLoaderQQNT-Plugin-QQPromote-1.5.0/src/renderer/domUpMessages.js:166:43)
at domUpMessages (local:////opt/LiteLoader/plugins/LiteLoaderQQNT-Plugin-QQPromote-1.5.0/src/renderer/domUpMessages.js:166:43) @ 
Uncaught TypeError: Cannot read properties of undefined (reading 'raw')
    at domUpMessages (local:////opt/LiteLoader/plugins/LiteLoaderQQNT-Plugin-QQPromote-1.5.0/src/renderer/domUpMessages.js:164:44)
at domUpMessages (local:////opt/LiteLoader/plugins/LiteLoaderQQNT-Plugin-QQPromote-1.5.0/src/renderer/domUpMessages.js:164:44) @ 
```

**Comment by Night-stars-1** [comment]
无法复现

**Comment by xmexg** [comment]
先冻结掉，以后再讨论吧
